### PR TITLE
Fix no-async-promise-executor warnings in backend

### PR DESCRIPTION
**Pull request by 2bit-hack**
Issue #54 

Replaced async promise executor functions with just async functions in `doCleanRemovedCourses` and `updateHeatmap` in `backend/utility/courseUtility.js` to remove ESLint's `no-async-promise-executor` warnings

### CODE REVIEW

**Comment by namsnath** [comment]
Hey,
I looked through the code. Instead of returning the error, can you throw it instead?
This way the route that calls the functions fails instead of just receiving an error value (which would need additional code to check). Throwing should allow the outer catch blocks to handle the error.

**Comment by namsnath** [comment]
I'll test and merge the code in the morning

**Comment by 2bit-hack** [comment]
> Instead of returning the error, can you throw it instead?

Will do

**Comment by namsnath** [comment]
Awesome!
I'll merge this now.

**Pull request merged**
