### PR TITLE
Screenshot and CSV downloads added.

### LINKED ISSUE #74: Add Screenshot/Save for timetable
There is no way to share/save timetables for now.

A useful feature would be to add a button that allows saving a screenshot of the timetable as a PNG/PDF or the course list as a CSV/TXT file.

Something like [this](https://www.npmjs.com/package/react-to-print) could be used, provided it keeps the CSS on print.

Exporting to a downloadable CSV/TXT file should be trivial.

### PR DESCRIPTION
**Pull request by brij1999**
# Details
* This PR aims to resolve #74 .
* It provides two buttons in the UI component just before the timetable, that allows the users to download the PNG image of timetable, and a CSV record of the selected courses.

# Updated UI

# CSV file
Screenshot from 2020-10-24 01-39-37

# Screenshots Captured
* Desktop version:
FFCSThingy - Timetable

* Mobile version:
FFCSThingy - Timetable (1)

### CODE REVIEW

**Comment by brij1999** [comment]
@namsnath please have a look, and do tell me if something needs to be updated : )

**Comment by brij1999** [comment]
@namsnath should I keep the base of PR as dev or master?

**Comment by namsnath** [comment]
Keep the base as dev please
I'll add comments after a bit, the screenshots look good tho

**Comment by namsnath** [comment]
Hi @brij1999, you seem to have branched off from master. 
Could you open a new PR branched off from dev like I mentioned in #74?

There are more changes required that I'll add in the new PR. 
Also, please commit the updated package.json and package-lock.json files in the new PR

**Comment by brij1999** [comment]
Omg I totally forgot about the local dev.
* Insert giant face-palm here *😅
On it bro.

**Comment by namsnath** [comment]
Yeah, a re-fork and copy-paste should do the job. There are some commits on master that are not on dev, which will be fixed in the next merge. 

And dev has changes which will break your code, so check those out too before the PR.

**Pull request closed without merging**
